### ISSUE TITLE
Vertical alignement of field names

### ISSUE THREAD

**Issue by linaGirl** [distributed-systems/recordr-chrome-extension#1]
![image](https://cloud.githubusercontent.com/assets/603475/12333020/141c5ce8-baf2-11e5-8228-9aacc2f052f4.png)

i propose to set the vertical alignement to top in order to make the layout a bit more clear

**Comment by linaGirl** [comment]
maybe a very light background color that gets darker for each level of validators would be better than the vertical alignement?

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/12649712/0efa1626-c5e0-11e5-91ea-989e363efc83.png)

**Comment by fxstr** [comment]
Removed the «add constraint» buttons (replaced with a +) and the «add property» button (only visible on hover) – should improve readability. further improvements would be lovely.

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/12649792/574539b0-c5e0-11e5-9d16-17a85bcb0b1a.png)

**Comment by fxstr** [comment]
@eventEmitter Do you think the coloring of the background helps? it's only displayed when hovering the corresponding elements.

**Comment by linaGirl** [comment]
@fxstr doesn't look exactly beautiful but it may be helpful?

**Comment by fxstr** [comment]
@eventEmitter beautifuler?

![image](https://cloud.githubusercontent.com/assets/1211144/12649991/601462ae-c5e1-11e5-944f-0184c529459e.png)
