### ISSUE TITLE
Settings have no effect

### ISSUE THREAD

**Issue by linaGirl** [distributed-systems/recordr-chrome-extension#2]
![image](https://cloud.githubusercontent.com/assets/603475/12333228/4a0550d4-baf3-11e5-9dbc-c824eca81dbb.png)

vs

![image](https://cloud.githubusercontent.com/assets/603475/12333234/534b9a40-baf3-11e5-8024-aaf8a3f34b14.png)

**Comment by fxstr** [comment]
Ah, bad wording/label: This field accepts Mime types: Enter «text/html» and text/html docs will not show up in the recorder. 

There should be more settings: 
- Response headers to ignore (that's what you propose, I guess)
- Ignore the following Mime types (current field, wrong label)
- Only record the following Mime types (overwrites «Ignore Mime types»)

**Comment by linaGirl** [comment]
also: request headers to ignore

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/12658810/9adf9bfe-c60b-11e5-99dc-f89f72b14f22.png)

**Comment by linaGirl** [comment]
nice!
