### ISSUE TITLE
Number, String detection in the response

### ISSUE THREAD

**Issue by linaGirl** [distributed-systems/recordr-chrome-extension#4]
It would be great if the correct type valdiation was selected for many of the fields.

![image](https://cloud.githubusercontent.com/assets/603475/12333729/42329b98-baf6-11e5-9815-4ac578272cf9.png)

Maybe using `/[^0-9]/.test(input)` ?

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/12652374/cbfa9a2a-c5ea-11e5-8640-c20b292f220e.png)

recognizes
- bool
- number
- date 
- string
