### ISSUE TITLE
Add the nullable and and optional flags for all validators

### ISSUE THREAD

**Issue by linaGirl** [distributed-systems/recordr-chrome-extension#6]

**Comment by linaGirl** [comment]
one must be able to set both flags on every property, setting it on he validators doesn't make sense. maybe i should implement a nullable and a optional validator. what do you think @fxstr ?

**Comment by fxstr** [comment]
![image](https://cloud.githubusercontent.com/assets/1211144/12675005/98338cfe-c687-11e5-8b22-94545105f94b.png)
- null values are recognized by the parser, nullable flag is automatically set
- every property may have a nullable and/or optional validator

**Comment by linaGirl** [comment]
perfect! thanks

**Comment by linaGirl** [comment]
is it possible not to set the array length on an array validator?

**Comment by fxstr** [comment]
by default you mean?

**Comment by linaGirl** [comment]
is it possible at all to not validate the length?

**Comment by fxstr** [comment]
by using >= 0, i'd say. or would you like to remove the whole length check?

**Comment by linaGirl** [comment]
ok, this should work in combination with the optional and nullable validator
